### ISSUE TITLE
Bad Request on adding a run with a certain map

### ISSUE THREAD

**Issue by janblumenkamp** [TechnoX/rcj-rescue-scoring#44]
![addrunbadrequest](https://user-images.githubusercontent.com/5030127/28200269-57ad3324-686b-11e7-9817-659cbf1482a0.png)
`POST http://localhost:3000/api/runs/line 400 (Bad Request)
(anonymous) @ angular.js:12701
q @ angular.js:12446
(anonymous) @ angular.js:12198
(anonymous) @ angular.js:17000
$digest @ angular.js:18182
$apply @ angular.js:18480
(anonymous) @ angular.js:27290
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121`

This may be related with Issue #37 
Only happens with a certain map.

**Comment by TechnoX** [comment]
It would be very good if I can get the output from the POST Response. You can see it if you expand the POST request in the console window.

Also if there is something in the backend terminal when this happens?

**Comment by TechnoX** [comment]
I would guess that Team 2 already have a Run in Round 1 and therefore can't be added. I added an pop-up error message for this in commit #e44b8ef

**Comment by janblumenkamp** [comment]
Ah okay, the problem was that I forgot to place a tile at the starting tile. There should have been a straight line under it, I just thought it was invisible/covered by the flags. Maybe add a popup that shows up when attempting to save an unfinished map (that is a map where the tile selected as start tile has no tile information)?

**Comment by TechnoX** [comment]
A better idea is to change the flags to another icon. The flag is confusing because it is a finish flag, indicating the goal not the start. We should change it to something that indicates a start. 

And make it not cover the line as much. 


And maybe also throw an error when trying to place it on a square without any tile-information (if that is easy to fix). 

I will take care of this later today!

**Comment by TechnoX** [comment]
The last thing we talked about here, about the starting tile is now fixed.
